In [2]:
import numpy as np

In [3]:
def sigmoid(x):
    s = 1/(1 + np.exp(-x))
    return s

x = np.array([1, 2, 3])
print(sigmoid(x))

[0.73105858 0.88079708 0.95257413]


In [4]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = s * (1-s)
    return ds

x = np.array([1, 2, 3])
ds = sigmoid_derivative(x)
print(ds)

[0.19661193 0.10499359 0.04517666]


In [5]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    x = x/x_norm
    return x
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
x = normalizeRows(x)
print(x)

[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
